### ISSUE TITLE
Error when adding more than three ViewControllers in "TinderStoryboard" example project

### ISSUE THREAD

**Issue by LuiggiMS** [StefanLage/SLPagingView#11]
Hi !
I have successfully run the project example in my iPhone but the problem appears when I try to add another UIViewController to the "TinderStoryboard" example project.
I have put  sl_3  into the storyboardSegue in the fourth UIViewController.
![captura de pantalla 2015-02-20 a las 11 16 13](https://cloud.githubusercontent.com/assets/5784472/6290067/5605b850-b8f2-11e4-93b6-8b7bd1fea5a3.png)
![captura de pantalla 2015-02-20 a las 11 16 20](https://cloud.githubusercontent.com/assets/5784472/6290127/9faada12-b8f2-11e4-8881-6c0083944018.png)
Anyone know the cause of this problem ? Thanks.

**Comment by StefanLage** [comment]
Hi @LuiggiMS 
I fixed the bug ecb84f80dcbc145cb35211c2c29ba06c717ab3aa.
Actually the method which add all views didn't sort views by index, thus it crashed but only using Auto Layout because it try to make a constraint with some views that weren't existing yet.

**Comment by LuiggiMS** [comment]
Thanks a lot :smiley:
