### ISSUE TITLE
Navigation bar background color

### ISSUE THREAD

**Issue by ghost** [StefanLage/SLPagingView#12]
Hi,

I was wondering if there is a way to change the navigation bar's background color using Storyboard. I saw that you manage it in `navigationBarView` but it's a private property, I can't change.

Thanks for the great work!

**Comment by StefanLage** [comment]
Hi @fabioknoedt 
Thanks for your feedback, I'll add a public method to change the navigation bar's color.
I'll also add a way to do it directly from the storyboard.
