### ISSUE TITLE
Add ability to hide the navigationBarView 

### ISSUE THREAD

**Issue by rodericj** [StefanLage/SLPagingView#15]
I'm looking to use SLPagingView on the top level of a UINavigationController stack, but hide it on all others. I've been playing with the implementation and I've found that by exposing the navigationBarView, I can hide this when necessary. I can create a pull request with the fix, but I wanted to get your thoughts on exposing this otherwise private attribute.

**Comment by StefanLage** [comment]
Fixed c42eed559a76650705c545400fb3e4217ce9d6dd
