### ISSUE TITLE
self.navigationController is null from the page

### ISSUE THREAD

**Issue by chlebta** [StefanLage/SLPagingView#19]
I'got project that's look like this : 
![5605b850-b8f2-11e4-93b6-8b7bd1fea5a3](https://cloud.githubusercontent.com/assets/1204608/6728798/fa0d6eb2-ce2c-11e4-97b0-2d4a42217922.png)

So the problem if I try to push view from one of the pager View (the red or yellow one ...) it won't work because self.navigationController is null, how to fix it ? {code Example to push view from the yellow screen}

```
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main"bundle:nil];
    PostReaderViewController *postReaderView =
    (PostReaderViewController *)
    [storyboard instantiateViewControllerWithIdentifier:@"postReaderView"];
    NSLog(@"%@", self.navigationController);
    [self.navigationController pushViewController:postReaderView animated:YES];
```

**Comment by StefanLage** [comment]
I fixed the viewControllers hierarchy so you can push a view from the navigationController of your parentViewController. 
Instead of `self.navigationController` use `self.parentViewController.navigationController`

**Comment by chlebta** [comment]
@StefanLage 
Note that my view are of different class, not subclass of
SLPagingViewController. Also after pushing when I click on back button it doesn't work.

On Thursday, March 19, 2015, Stefan Lage notifications@github.com wrote:

> I fixed the viewControllers hierarchy so you can push a view from the
> navigationController of your parentViewController.
> Instead of self.navigationController use
> self.parentViewController.navigationController
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StefanLage/SLPagingView/issues/19#issuecomment-83691336
> .

## 

Regards :
Kaouach Ahmed Alaeddine
Software Engineer
chlebta.com  / about.me/chlebta

**Comment by StefanLage** [comment]
The back button doesn't work because the view `self.navigationBarView` is in front of the navigationBar so you can't tap on it.
I did a ugly trick to "fix" it. a8354776e60a11529cf2c680717d12794f550f25

**Comment by chlebta** [comment]
Yeah thank's you saved my day :dancers:  the Library is really cool, sorry for much trouble I caused I'm just new IOS developer and you know how much painful the junior phase.
Also I'got another post have you check it ?

**Comment by StefanLage** [comment]
No worries it's fine.
Yes I saw the issue #18, actually the last commit fix a part of it but I don't like the way I did it so I let it open as a reminder for the next big release.

**Comment by chlebta** [comment]
@StefanLage  the ugly thing you did have deactivated also the click on the menu button on the home page :/  .
Also there's bug when removing observer so I'd to desactivate ([NSNotificationCenter defaultCenter] addObserver and RemoveObserve)

**Comment by harkmall** [comment]
I'm still having issues with this, self.parentViewController.navigationController is also null
