### ISSUE TITLE
Issue with Two Pointers

### ISSUE THREAD

**Issue by bevbomb** [StefanLage/SLPagingView#2]
I'm not sure if this was a typo or what, but you've set up these two pointers like so

typedef void(^SLPagingViewMoving)(NSArray *subviews);
typedef void(^SLPagingViewMovingRedefine)(UIScrollView *scrollView, NSArray *subviews);

But your referencing one like this 

pageViewController.pagingViewMoving = ^(UIScrollView _scrollView, NSArray *subviews){
        CGFloat xOffset = scrollView.contentOffset.x;
        int i = 0;
        for(UILabel *v in subviews){
            CGFloat alpha = 0.0;
            if(v.frame.origin.x < 145)
                alpha = 1 - (xOffset - i_320) / 320;
            else if(v.frame.origin.x >145)
                alpha=(xOffset - i*320) / 320 + 1;
            else if(v.frame.origin.x == 140)
                alpha = 1.0;
            i++;
            v.alpha = alpha;
        }
    };

which throws a Fatal Error in Xcode 6 because the block your referencing doesn't contain "scrollView"

**Comment by Insider77** [comment]
Looks like a typo. If I remove "UIScrollView *scrollView" from reference it works ok with TinderType. Like so:

pageViewController.pagingViewMoving = ^(NSArray _subviews){
CGFloat xOffset = scrollView.contentOffset.x;
int i = 0;
for(UILabel *v in subviews){
CGFloat alpha = 0.0;
if(v.frame.origin.x < 145)
alpha = 1 - (xOffset - i320) / 320;
else if(v.frame.origin.x >145)
alpha=(xOffset - i_320) / 320 + 1;
else if(v.frame.origin.x == 140)
alpha = 1.0;
i++;
v.alpha = alpha;
}
};

But still throws an error if using TwitterType

**Comment by inb4ohnoes** [comment]
Just change `pagingViewMoving` to `pagingViewMovingRedefine` until the author fixes this.

**Comment by StefanLage** [comment]
Both issues are fixed in the last two commit a005da0816d3d29138fae42893fc38e4d0086933 ae0828d4fb775dedcce7db82b38a3ab7f154289e
