### ISSUE TITLE
View Controllers get deallocated

### ISSUE THREAD

**Issue by harkmall** [StefanLage/SLPagingView#30]
When I present the paging view with my three view controllers, they are all deallocated. Is there a reason they are not kept around?

**Comment by alexcosmin** [comment]
I am facing the same issue. Did you find a solution to this problem, @golfguru1 ?

**Comment by harkmall** [comment]
@alexcosmin I have my SLPagingView inside a navigation controller so I just keep a strong reference to the view controllers in it inside the root of the navigation controller. Not pretty, but it works.
