### ISSUE TITLE
please enable auto resize

### ISSUE THREAD

**Issue by iblacksun** [StefanLage/SLPagingView#6]
I'm using [KNSemiModalViewController](https://github.com/kentnguyen/KNSemiModalViewController) and  SLPagingView together, but SLPagingView.scrollview frame is fixed, so subview's contentSize and frame is wrong.

**Comment by StefanLage** [comment]
I've added AutoLayout support 9dd3afd7add43c714b0dd8d191de9491f5430a5b
Now it should be right.
