### ISSUE TITLE
Couldn't correct implement with controllers.

### ISSUE THREAD

**Issue by SergeyOleynich** [StefanLage/SLPagingView#8]
Please can You explain me what I do wrong?
In my appDelegate
# import "AppDelegate.h"
# import "SLPagingViewController.h"
# import "ChatViewController.h"
# import "ProfileViewController.h"
# import "SettingsViewController.h"
# import "MainViewController.h"

@interface AppDelegate ()

@end

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Override point for customization after application launch.
  
  UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
  
  ChatViewController *chat = (ChatViewController *)[storyboard instantiateViewControllerWithIdentifier:@"Chat"];
  ProfileViewController *profile = (ProfileViewController *)[storyboard instantiateViewControllerWithIdentifier:@"Profile"];
  SettingsViewController *settings = (SettingsViewController *)[storyboard instantiateViewControllerWithIdentifier:@"Settings"];
  
  SLPagingViewController *pageViewController  = [[SLPagingViewController alloc] initWithNavBarControllers:@[settings, chat, profile]];
  
  UINavigationController *navC = [[UINavigationController alloc] initWithRootViewController:pageViewController];
  
  //UINavigationController *nc = [[­UINavigationController alloc] initWithRootViewController:pageViewController];
  
  //self.window.rootViewController = pageViewController;
  self.window.rootViewController = navC;
  
  return YES;
  }

Then in my ChatController:
-(void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    NSLog(@"APPEAR");
}

-(void)dealloc{
    NSLog(@"DEALLOC");
}

and in my console I see only DEALLOC. And APPEAR I didn't see.
Please explain what I am doing wrong?

**Comment by StefanLage** [comment]
Actually the library never call “viewDidAppear“ that’s why the controller doesn’t know its view appeared.
Thanks for notifying me about this,  I’ll add this feature ASAP.

**Comment by SergeyOleynich** [comment]
ok) What about the block "SLPagimgViewDidChange"? When i implement it i notice my appDelegate about current index of controller. But if my controller was dealloc it mean that it was kill? But I can call the public method from my controller?Would it be correct?

**Comment by StefanLage** [comment]
I fixed the missing call "viewDidAppear" c38d8da894c7470228bd0665f0a2d3ef0c79647c. Now you should be aware when a view appeared.

The library didn't retain the controllers which means they all were **dealloc** (as you said they were killed). 
An object deallocated has its release count goes down to zero, which means that the object reference points to a random position (generally it points to the **garbage**). So If you tried to call a method from one of them it used to crash with `EXC_BAD_ACCESS` because your reference pointed to a memory position that can't be interpreted as an object.

About the current index, I let you refer to your other issue #7.

**Comment by SergeyOleynich** [comment]
Thanks)I'll try it)

**Comment by chlebta** [comment]
I'm trying to implement this library and I've used the same code as @SergeyOleynich  and I've attributed to to my view in storyboard **SLPaggingViewController** class but my app stuck in this line (line 216 SLPagingViewController.m) 

![capture d ecran 2015-03-13 a 10 33 41](https://cloud.githubusercontent.com/assets/1204608/6636054/abf80abc-c96c-11e4-98a2-f9ef2b2d0844.png)

and never skip it
